---
title: "Plotly plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r, include=FALSE}
library(p8105.datasets)
library(tidyverse)
library(plotly)
library(flexdashboard)

data("rest_inspec")

nyc_rest = 
  rest_inspec %>% 
  select(boro, critical_flag, cuisine_description, dba, zipcode, score, grade, grade_date) %>% 
  filter(
    !is.na(grade)
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nyc_rest %>% 
  count(grade, boro) %>% 
  mutate(
    grade = fct_reorder(grade, n)) %>%
  filter(
    grade %in% c("A", "B", "C"),
    boro != "Missing"
    ) %>% 
  plot_ly(
    x = ~boro, y = ~n, color = ~grade, type = "bar", colors = "viridis"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
nyc_rest %>% 
  filter(boro != "Missing") %>% 
  count(grade_date, boro) %>%
  plot_ly(
    x = ~grade_date, y = ~n, type = "scatter", color = ~boro, mode = "markers", colors = "viridis", alpha = 0.5
  )
```

### Chart C

```{r}
nyc_rest %>% 
  filter(str_detect(dba, "[Bb][Aa][Gg][Ee][Ll]")) %>% 
  group_by(boro, score) %>% 
  plot_ly(
    x = ~boro, y = ~score, type = "box", color = ~boro, colors = "viridis"
  )
```





